-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco on \'Telepathy and the Spiritural World\'','411','910c1c51-6f1a-412f-8ae8-d26931bd8fba','Not transcribed','2010/09/10 01:32:26','2010/09/10 03:22:22','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco on the Discovery Channel (Repository)','200','d9d2d32e-45dd-47ec-a750-ef02bd6fafae','Not transcribed','2010/09/09 22:25:42','2010/09/09 22:31:07','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco on the Discovery Channel','200','7435f620-99ce-451a-8069-4aa3a9a615e5','3 Translations','2010/09/09 20:37:48','2010/09/10 01:15:52','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('RSA Animate - The Empathic Civilization (Repository) ','639','6f9b13eb-a241-45b0-a300-c6a868e4d4b5','Transcribed','2010/09/06 03:54:13','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco\'s full interview with Larry King, 1974','2535','305345b2-5b60-4abe-8a20-3cdfa1394ddb','Not transcribed','2010/07/28 18:07:08','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('The Zeitgeist Movement - an Introduction','1753','9f093b88-3382-459d-9e1e-a1302abb35ce','Not transcribed','2010/07/14 20:40:31','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Interview with Peter Joseph - Luminopolis London 2008','2192','74b997de-7e89-4108-8378-ffa2159d3032','Not transcribed','2010/07/14 07:26:47','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Peter Joseph Interview by Eerie Investigations 2008-11-29','2739','e4e7495f-8075-4adb-a148-cc3d29728f9b','Not transcribed','2010/07/14 04:35:55','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('The Future of Economics - A Perspective from The Zeitgeist Movement (Repository)','4358','59c957ad-9ba4-45fa-a56e-8dc6995be460','Not transcribed','2010/07/05 10:09:40','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('The Future of Economics - A Perspective from The Zeitgeist Movement','4358','cf0f91f3-8133-4982-ae43-2479e6253a2c','Not transcribed','2010/07/05 09:17:40','2010/09/10 01:53:19','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('RSA Animate - Crises of Capitalism (Repository)','670','8303ec26-2ae9-4dde-a1ec-3bc1e0e7da43','Not transcribed','2010/07/05 06:00:21','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('RSA Animate - Crises of Capitalism','672','a241d747-ffa4-4593-bba7-a04bb4323358','Not transcribed','2010/07/01 04:41:56','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Peter Joseph\'s \'Where are We Going?\' lecture - Nov 15, 2009 (Repository)','7239','ad0d761a-ae97-4861-b3c7-9db72b621044','Not transcribed','2010/06/12 05:53:32','2010/09/08 16:11:26','http://dotsub.com/view/0e384aec-6a3b-46b5-ae7e-1250ebba4794','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Peter Joseph\'s \"Where are we now?\" - July 25, 2009 London (Final Proofreading)','4135','e3f20f9f-101b-4492-83b0-814b46cece67','Not transcribed','2010/06/12 05:33:11','2010/09/08 16:11:26','http://dotsub.com/view/dd83d532-7fcd-4a5c-a7f5-58f245ab4fe6','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco and Roxanne Meadows on \"On The Edge, with Theo Chalmers\"','5997','095ad035-5acc-4c5b-b365-6863f51343e1','Not transcribed','2010/06/11 08:03:10','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('RSA Animate - The Empathic Civilization','639','cefe3990-0ee4-4617-a3db-f5edf766c189','2 Translations','2010/05/19 08:43:40','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Talk Series - 2nd Edition ','517','076abb51-1606-4e69-b7dc-94c309d6bc7f','Not transcribed','2010/05/19 08:24:44','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Fresco talk- July 26, 2009 ','567','b122bdb4-3216-43bf-8b4c-d27020dc4b11','Not transcribed','2010/05/19 05:35:28','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Höskuldur Eyjólfsson\'s \'Ashamed of being human\'','1656','ddd54606-76aa-4a95-a107-d810f58af59d','Not transcribed','2010/05/15 22:26:56','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Who is Peter Joseph? (Repository)','2971','651bf2b8-e222-443f-b1c9-bef709b10dd4','3 Translations','2010/05/12 07:50:02','2010/09/08 23:26:22','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco on the problem of superstitious ignorance (Repository)','454','c2f95981-60ae-4673-990c-78a4a540328e','1 Translations','2010/05/11 06:05:50','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Doug Mallette\'s \'Our Technical Reality\'','2986','594e2dce-958c-4a4a-8209-db8f1d013681','Not transcribed','2010/05/05 01:27:51','2010/09/10 03:41:54','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Zeitgeist: Addendum (Final Proofreading project)','7386','b47a0565-0e49-40ba-a6b3-e7d5961ecc8b','Not transcribed','2010/05/02 11:27:15','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('The Zeitgeist Movement: Orientation Presentation (Final Proofreading project)','5825','bfce5a1c-fc5b-4771-94fe-9f17d6531ab2','Not transcribed','2010/05/02 11:16:17','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Peter Joseph on Social Pathology - Z-Day 2010 in NYC (Repository)','6292','bbe64ec7-c1e1-43b3-82b5-5ed809b174c6','1 Translations','2010/05/02 04:49:39','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco New Zealand FULL TV Interview (25:04), April 2010 (Repository)','1504','fbb6f0bc-2c70-4708-a063-27b9c81d219f','2 Translations','2010/05/01 00:56:56','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco New Zealand TV Interview (5:53), April 2010 (Repository)','353','a08861c1-8910-4af8-9066-cfdc6cb574f3','2 Translations','2010/04/30 22:29:04','2010/09/08 23:51:01','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco New Zealand FULL TV Interview (25:04), April 2010','1504','2b1f1134-10ba-4216-9108-28d947e10d47','6 Translations','2010/04/30 10:58:29','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Ben McLeish Presents - Common Objections, Observations, Responses (Repository)','1253','482f9113-c1a3-4af9-b039-e9e2deee6e43','Transcribed','2010/04/17 09:19:58','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco snippets from Zday NY 2010 (Repository)','599','48f3fed1-7f7a-4188-8224-f83e03549fc2','2 Translations','2010/04/17 07:00:28','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco New Zealand TV Interview (5:53), April 2010','353','99cec389-f405-48b7-bfbd-9965c1d3789e','7 Translations','2010/04/17 03:26:10','2010/09/08 23:34:49','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Z-Day 2010 Opening','459','8a9b4ab5-0cb6-4ebb-af83-d4b32c5f39e8','12 Translations','2010/04/16 10:18:23','2010/09/09 09:01:30','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Ben McLeish Presents - Common Objections, Observations, Responses','1253','051f4233-45d1-471d-96f1-99cf6642a854','3 Translations','2010/04/12 06:38:22','2010/09/09 20:00:55','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Z-Day 2010 Opening (Repository)','459','88f4da77-efb6-4562-8c91-b6b1c8f4eab7','1 Translations','2010/04/10 04:20:40','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Peter Joseph on Social Pathology - Z-Day 2010 in NYC','6292','a3bb7c17-b2c8-40ec-9df4-3ced304695b5','13 Translations','2010/04/09 11:42:34','2010/09/09 07:34:14','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Z-Day March 13, 2010 NYC (1 of 6)','5607','b10af39d-3eb9-4573-bbb3-7fd50739ddaf','Not transcribed','2010/03/21 20:42:47','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Roxanne Meadows - Zday 2010 (2 of 2)','404','7370c480-7b54-4acb-9ebd-f3b20513d8d0','Not transcribed','2010/03/20 10:09:04','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Roxanne Meadows - Zday 2010 (1 of 2)','600','46fa3d1e-4802-4886-bf6c-58926bcaf7c6','1 Translations','2010/03/20 09:37:11','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Jacque Fresco snippets from Zday NY 2010','599','37c24609-13de-4f0a-a8fa-007899be1205','7 Translations','2010/03/16 09:04:21','2010/09/08 16:11:26','','');

INSERT INTO projects (`title`,`length`,`dotsub_id`,`work_status`,`date_create`,`last_modified`,`external_identifier`,`uri`) VALUES ('Who is Peter Joseph?','2971','aa1cef2a-7cb1-4aa0-90bc-898db604c509','21 Translations','2010/03/01 11:32:01','2010/09/08 23:29:24','','');